name: Pull Request Build

permissions:
  id-token: write
  contents: read
  
on:
  pull_request:
    types: [ "opened", "reopened", "synchronize",  ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.build.outputs.version}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_ROLE }}
      - name: Build with Maven
        id: build
        run: |
          mvn -B -V -ntp clean package
